import type { ApInvoice } from "./ap-types";

function pad2(n: number) {
  return String(n).padStart(2, "0");
}

function toIso(d: Date) {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

function addDays(iso: string, days: number) {
  const d = new Date(iso + "T00:00:00");
  d.setDate(d.getDate() + days);
  return toIso(d);
}

/**
 * Mock vendor bills relative to `asOf` so aging, discounts, and the 14-day
 * calendar stay realistic whenever the page loads.
 */
export function getMockApInvoices(asOf: Date = new Date()): ApInvoice[] {
  const today = toIso(asOf);

  return [
    // —— Open, current / upcoming ——
    {
      id: "ap-001",
      vendorName: "Oxford Nursery Supply",
      category: "Materials",
      invoiceDate: addDays(today, -12),
      dueDate: addDays(today, 5),
      amount: 4280,
      status: "open",
      discountPercent: 2,
      discountDeadline: addDays(today, 3),
    },
    {
      id: "ap-002",
      vendorName: "Mid-South Fuel Co-op",
      category: "Fuel",
      invoiceDate: addDays(today, -8),
      dueDate: addDays(today, 7),
      amount: 1860.5,
      status: "open",
      discountPercent: 1.5,
      discountDeadline: addDays(today, 2),
    },
    {
      id: "ap-003",
      vendorName: "GreenScape Insurance Group",
      category: "Insurance",
      invoiceDate: addDays(today, -20),
      dueDate: addDays(today, 10),
      amount: 9200,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-004",
      vendorName: "FleetLease Partners",
      category: "Equipment Financing",
      invoiceDate: addDays(today, -5),
      dueDate: addDays(today, 12),
      amount: 3750,
      status: "open",
      discountPercent: 1,
      discountDeadline: addDays(today, 6),
    },
    {
      id: "ap-005",
      vendorName: "Jobber SaaS",
      category: "Subscriptions",
      invoiceDate: addDays(today, -3),
      dueDate: addDays(today, 14),
      amount: 289,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-006",
      vendorName: "Delta Mulch & Soil",
      category: "Materials",
      invoiceDate: addDays(today, -2),
      dueDate: addDays(today, 9),
      amount: 2150,
      status: "open",
      discountPercent: 2,
      discountDeadline: addDays(today, 8),
    },
    {
      id: "ap-007",
      vendorName: "Shell Business Fleet",
      category: "Fuel",
      invoiceDate: addDays(today, -1),
      dueDate: addDays(today, 13),
      amount: 942.25,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },

    // —— Open, aged ——
    {
      id: "ap-008",
      vendorName: "Southern Irrigation Parts",
      category: "Materials",
      invoiceDate: addDays(today, -45),
      dueDate: addDays(today, -18),
      amount: 1680,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-009",
      vendorName: "Kubota Financial",
      category: "Equipment Financing",
      invoiceDate: addDays(today, -70),
      dueDate: addDays(today, -40),
      amount: 5400,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-010",
      vendorName: "QuickBooks Online",
      category: "Subscriptions",
      invoiceDate: addDays(today, -95),
      dueDate: addDays(today, -65),
      amount: 175,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-011",
      vendorName: "Mississippi Liability Mutual",
      category: "Insurance",
      invoiceDate: addDays(today, -120),
      dueDate: addDays(today, -95),
      amount: 4100,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-012",
      vendorName: "Rebel Turf Products",
      category: "Materials",
      invoiceDate: addDays(today, -35),
      dueDate: addDays(today, -8),
      amount: 890,
      status: "open",
      discountPercent: 1,
      discountDeadline: addDays(today, -20),
    },
    {
      id: "ap-013",
      vendorName: "Pilot Flying J Fleet",
      category: "Fuel",
      invoiceDate: addDays(today, -55),
      dueDate: addDays(today, -25),
      amount: 1320,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },

    // —— Paid (for DPO credit-purchases window) ——
    {
      id: "ap-014",
      vendorName: "Oxford Nursery Supply",
      category: "Materials",
      invoiceDate: addDays(today, -40),
      dueDate: addDays(today, -10),
      amount: 3100,
      status: "paid",
      discountPercent: 2,
      discountDeadline: addDays(today, -25),
    },
    {
      id: "ap-015",
      vendorName: "Mid-South Fuel Co-op",
      category: "Fuel",
      invoiceDate: addDays(today, -28),
      dueDate: addDays(today, 2),
      amount: 1540,
      status: "paid",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-016",
      vendorName: "FleetLease Partners",
      category: "Equipment Financing",
      invoiceDate: addDays(today, -60),
      dueDate: addDays(today, -30),
      amount: 3750,
      status: "paid",
      discountPercent: 1,
      discountDeadline: addDays(today, -45),
    },
    {
      id: "ap-017",
      vendorName: "GreenScape Insurance Group",
      category: "Insurance",
      invoiceDate: addDays(today, -75),
      dueDate: addDays(today, -45),
      amount: 9200,
      status: "paid",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-018",
      vendorName: "Samsara Telematics",
      category: "Subscriptions",
      invoiceDate: addDays(today, -22),
      dueDate: addDays(today, 8),
      amount: 640,
      status: "paid",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-019",
      vendorName: "Delta Mulch & Soil",
      category: "Materials",
      invoiceDate: addDays(today, -50),
      dueDate: addDays(today, -20),
      amount: 1875,
      status: "paid",
      discountPercent: 2,
      discountDeadline: addDays(today, -35),
    },
    {
      id: "ap-020",
      vendorName: "John Deere Financial",
      category: "Equipment Financing",
      invoiceDate: addDays(today, -15),
      dueDate: addDays(today, 15),
      amount: 6200,
      status: "open",
      discountPercent: 1.5,
      discountDeadline: addDays(today, 4),
    },
    {
      id: "ap-021",
      vendorName: "SiteOne Landscape Supply",
      category: "Materials",
      invoiceDate: addDays(today, -18),
      dueDate: addDays(today, 4),
      amount: 3560,
      status: "open",
      discountPercent: 2,
      discountDeadline: addDays(today, 1),
    },
    {
      id: "ap-022",
      vendorName: "Adobe Creative Cloud",
      category: "Subscriptions",
      invoiceDate: addDays(today, -10),
      dueDate: addDays(today, 11),
      amount: 84.99,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-023",
      vendorName: "Workers Comp of the South",
      category: "Insurance",
      invoiceDate: addDays(today, -85),
      dueDate: addDays(today, -55),
      amount: 2750,
      status: "open",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-024",
      vendorName: "ExxonMobil Fleet Card",
      category: "Fuel",
      invoiceDate: addDays(today, -100),
      dueDate: addDays(today, -70),
      amount: 2105.4,
      status: "paid",
      discountPercent: null,
      discountDeadline: null,
    },
    {
      id: "ap-025",
      vendorName: "SiteOne Landscape Supply",
      category: "Materials",
      invoiceDate: addDays(today, -6),
      dueDate: addDays(today, 8),
      amount: 1240,
      status: "open",
      discountPercent: 2,
      discountDeadline: addDays(today, 5),
    },
  ];
}
